;----------------------------------------------------------------------------
; @(#)$CDS: assura version av4.1:Production:dfII6.1.5-64b:IC6.1.5-64b.500.17 08/31/15 04:19 (sjfql463) $
; sub-version 4.1_USR4_HF25
;----------------------------------------------------------------------------


;----------------------------------------------------------------------------
; Assura 3.2 Template Version 1
;----------------------------------------------------------------------------

vuiRcxSetupFormOptions = '(
    ((?vuiRCXFlowTab)
        (extractMosAp      nil)
        (resPropIdentifier      "r")
        (vuiOutputFormatLvsExtractedViewButton      t)
        (extractMosDiff      "NONE")
        (subNode      nil)
        (callProc      "")
        (mindPropIdentifier      "k")
        (parasiticCapComp      "pcapacitor")
        (checkCellView      nil)
        (parasiticIndComp      "pinductor")
        (vuiOutputFormatSpectreButton      t)
        (parasiticResComp      "presistor")
        (libPrefix      "")
        (vuiOutputFormatDspfButton      t)
        (ind1PropIdentifier      "ind1")
        (indPropIdentifier      "l")
        (parasiticMIndComp      "pmind")
        (capPropIdentifier      "c")
        (vuiRCXDefaultOutputFormatType      "Spice")
        (vuiOutputFormatSpiceButton      t)
        (vuiOutputFormatExtractedViewButton      t)
        (extractMosRes      nil)
        (vuiOutputFormatSpefButton      t)
        (vuiOutputFormatTransistorSpefButton      t)
        (ind2PropIdentifier      "ind2")
        (vuiOutputFormatTransistorDspfButton      t)
    )
    ((?vuiRCXExtractionTab)
        (refNode      "")
        (vuiRCXSP      t)
        (splitPinDistance      "5")
        (vuiRCXRCOnly      t)
        (vuiRCXEnableRCXFS      t)
        (temperature      "25.0")
        (vuiRCXEN      t)
        (vuiRCXCOnly      t)
        (peecMode      nil)
        (globalFrequency      "0")
        (vuiRcxFSExtractionCheckLimit      "NONE")
        (vuiRCXFSSN      nil)
        (vuiRCXSNP      t)
        (vuiRCXROnly      t)
        (vuiRCXEHrcx      t)
        (Maxfracturelength      "infinite")
        (excludeViaCap      nil)
        (vuiRCXRLC      t)
        (rcxfsHigh      nil)
        (vuiRCXFSEN      nil)
        (ladderNetwork      nil)
        (vuiRcxExtractionCheckLimit      "Full Chip All Nets")
        (vuiRCXFCSN      t)
        (netNameSpace      "Layout Names")
        (splitPins      nil)
        (multFactor      "1.0")
        (vuiRCXRLCK      t)
        (vuiRCXFCAN      t)
        (vuiRCXExtractDefault      "R Only")
        (vuiRCXFSFCAN      nil)
        (fractureLengthUnits      "microns")
        (vuiRCXFSSP      nil)
    )
    ((?vuiRCXFilteringTab)
        (vuiRCXexcludeSelfCapsReadOnly      nil)
        (vuiRCXArrayViasSpacing      "auto")
        (vuiRCXexcludeSelfCaps      nil)
        (vuiRCXmergeParallelR      nil)
        (vuiRCXmFactorWReadOnly      nil)
        (vuiRCXmFactorW      nil)
        (vuiRCXminCByPerc      "0.1")
        (vuiRCXminC      "0.01")
        (vuiRCXmFactor      "infinite")
        (vuiRCXDanglingR      nil)
        (vuiRCXMaxMergedViaSizeReadOnly      nil)
        (vuiRCXreduceRC      nil)
        (vuiRCXexcludeFloatingNetsReadOnly      nil)
        (vuiRCXexcludeFloatLimitReadOnly      nil)
        (vuiRCXminCReadOnly      nil)
        (vuiRCXminR      "0.001")
        (vuiRCXmergeParallelRReadOnly      nil)
        (vuiRCXexcludeFloatLimit      "2000000")
        (vuiRCXreduceRCReadOnly      nil)
        (vuiRCXexcludeFloatingNets      nil)
        (vuiRCXArrayViasSpacingReadOnly      nil)
        (vuiRCXFilterSizeReadOnly      nil)
        (vuiRCXMaxMergedViaSize      "auto")
        (vuiRCXmFactorReadOnly      nil)
        (vuiRCXminRReadOnly      nil)
        (vuiRCXFilterSize      "2.0")
        (vuiRCXDanglingRReadOnly      nil)
    )
    ((?vuiRCXNetlistingTab)
        (vuiRCXXy_c      nil)
        (vuiRCXAddExplicitVias      nil)
        (vuiRCXOutputNetNameSpace      "Schematic")
        (vuiRCXImportGlobals      nil)
        (vuiRCXXy_C      nil)
        (vuiRCXParasiticResModels      "Include As Comment")
        (vuiRCXXy_R      nil)
        (vuiRCXViaEffectOff      nil)
        (vuiRCXCouplingValues      "Double")
        (vuiRCXParasiticCapModels      "Include Model")
        (vuiRCXXy_D      nil)
        (vuiRCXIgnoreNets      "")
        (vuiRCXIgnoreLayer      "")
        (vuiRCXCapModels      "Do Not Include")
        (vuiRCXBusBit      "[]")
        (vuiRCXHierarchyDelimiter      "/")
        (vuiRCXParasiticResLength      nil)
        (vuiRCXXy_M      nil)
        (vuiRCXSubNodeChar      "#")
        (vuiRCXInstanceOff      nil)
        (vuiRCXResModels      "Do Not Include")
        (vuiRCXXy_Q      nil)
        (vuiRCXXy_r      nil)
        (vuiRCXstampingOff      nil)
        (vuiRCXDeviceFingerDelimiter      "@")
        (vuiRCXVirtualMetalFill      "Fine Shape")
        (vuiRCXSaveFillShapes      nil)
        (vuiRCXParasiticResWidth      "Off")
    )
    ((?vuiRCXRunDetailsTab)
        (vuiRCXLSFButton      t)
        (machineLoc      "local")
        (vuiRcxMp      nil)
        (vuiRcxRunMode      "Multi Processing")
        (vuiRCXMultiMachineButton      t)
        (vuiRcxNumOfP      "")
        (vuiRcxTempDir      "/tmp")
    )

)
