*******************************************************************************
****** common_source_amp schematic EE140_LAB0  <vs>  common_source_amp layout EE140_LAB0
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45rnspp) RES                                    1       2*
(g45n1svt) MOS                                    1       2*
                                             ------  ------
Total                                             2       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    1       2*          1       1
(g45rnspp) RES                                    1       2*          1       1
                                             ------  ------      ------  ------
Total                                             2       4           2       2

Schematic and Layout Match
